#!/usr/bin/env python3

import sys

mapped = {}

try:
    with open( sys.argv[ 1 ] ) as input:
        for line in input:
            if line.startswith( '#define ' ):
                define, name, number = line.split()
                value = int( number, 0 )

                if ( value < 0x80 )          \
                or ( ( value >> 8 ) == 0xFF ):
                    mapped[ value ] = name

    for value, name in sorted( mapped.items() ):
        print( f'X( 0x{value:04X}, "{name}" )' )

except Exception as exception:
    print( exception )
