#!/usr/bin/env bash
#
# ldupdate LIBDIR [...]
#
# This shell script maintains a specific shared-libraries
# configuration file, containing the paths of directories
# into which software has installed their libraries.

# The specific shared-library configuration file.
CONFNAME=awo-so-dirs.conf
CONFPATH=/etc/ld.so.conf.d
CONFFILE=${CONFPATH}/${CONFNAME}

# Process each given argument as a shared-library directory.
for ARG in "$@"
do
    # Canonicalize the argument (will not have a trailing slash).
    LIBDIR=$(realpath -e "${ARG}")

    # See if the shared-library directory is already listed.
    if [[ ${LIBDIR} ]] && ! grep -Eqxs "${LIBDIR}" ${CONFFILE}
    then
        # Directory not yet listed - add it to the configuration file.
        echo "${LIBDIR}" >>${CONFFILE}

        # Report the action.
        echo>&2 "Added '${LIBDIR}' to '${CONFFILE}'"

        # Update the running cache in this session.
        ldconfig "${LIBDIR}"
    fi
done
